modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="examplemod"
version="${file.jarVersion}"
displayName="Warium API Example Mod"
description='Small example mod showing Warium API usage.'

[[dependencies.examplemod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.examplemod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.examplemod]]
modId="wariumapi"
mandatory=true
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"
